
import express, { Request, Response } from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());

// Initialize server-side Gemini client
const apiKey = process.env.GEMINI_API_KEY;
let ai: GoogleGenAI | null = null;
if (apiKey) {
  ai = new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

// Fallback response generator for domain-specific queries when key is not present
function generateFallbackResponse(message: string, context?: any): string {
  const lower = message.toLowerCase();
  const q = context?.activeQuestion;

  if (lower.includes('hint')) {
    if (q) {
      return `💡 **Nexus AI Hint for ${q.id}**:
1. Identify the core principle: this question evaluates **${q.topic}**.
2. Notice the constraints: ${q.questionType === 'NAT' ? 'This is a Numerical Answer Type question without negative marking.' : `Focus on eliminating false options based on edge conditions.`}
3. ${q.explanation?.shortcutTrick ? `**Key observation:** ${q.explanation.shortcutTrick}` : 'Calculate the state step-by-step before choosing your answer.'}`;
    }
    return `💡 **Nexus AI Hint**: Consider the fundamental mathematical definition first. Check boundary conditions (n=0, n=1, or initial states) to eliminate incorrect possibilities quickly.`;
  }

  if (lower.includes('explain') || lower.includes('solve') || lower.includes('solution') || lower.includes('this')) {
    if (q) {
      return `### 📘 Step-by-Step Nexus AI Solution for ${q.id}
**Subject:** ${q.subject} · **Topic:** ${q.topic} · **Marks:** ${q.marks} Mark(s)

#### 1. Problem Statement Analysis
We are tasked with solving:
> ${q.questionText.slice(0, 180)}...

#### 2. Concept Tested
${q.explanation?.conceptTested || 'Core architectural and algorithmic principles relevant to GATE.'}

#### 3. Step-by-Step Derivation
${q.explanation?.steps?.map((step: string, idx: number) => `${idx + 1}. ${step}`).join('\n') || 'Follow the fundamental state transitions.'}

#### 4. Correct Result
- **Correct Answer:** \`${q.correctAnswer}\`
- **Common Trap:** ${q.explanation?.commonMistake || 'Watch out for index offsets and arrival time assumptions.'}
- **Speed Shortcut:** ${q.explanation?.shortcutTrick || 'Use standard formulas to avoid re-deriving during the 3-hour exam.'}`;
    }
  }

  if (lower.includes('similar') || lower.includes('practice question')) {
    return `🎯 **Similar Practice Question Generated by Nexus AI**:

**Topic:** ${context?.activeTopic || 'Operating Systems - Process Scheduling'} (GATE Pattern)
**Question Type:** MCQ | **Marks:** 2

**Question:**
Consider 3 processes arriving at time 0 with burst times P1=6ms, P2=8ms, P3=2ms scheduled using Round Robin with time quantum q = 2ms. What is the average waiting time?

**Options:**
- A) 4.33 ms
- B) 5.67 ms
- C) 6.00 ms
- D) 3.66 ms

*Hint: Draw the round-robin queue after each 2ms time slice to track process re-entry!*`;
  }

  if (lower.includes('plan') || lower.includes('study plan') || lower.includes('schedule')) {
    return `📅 **Personalized GATE Preparation Plan (Next 4 Weeks)**:

- **Week 1: High-Weightage Core (Algorithms & DS)**
  - Master Recurrences, Dynamic Programming (0/1 Knapsack, LCS), and Graph Traversals (Dijkstra, Bellman-Ford).
  - Solve at least 40 PYQs (2018–2025).

- **Week 2: Operating Systems & COA**
  - CPU Scheduling (SRTF, Round Robin), Deadlock Banker's Algorithm, Multi-level Paging.
  - COA: 5-stage Pipelining hazard stall formulas, Direct/Set-associative cache mappings.

- **Week 3: DBMS & Computer Networks**
  - Normalization (Lossless join, BCNF/3NF decomposition), Serializability graphs.
  - TCP Congestion Control (Slow Start & Reno), CIDR Subnetting.

- **Week 4: Mock Tests & Revision**
  - Take 2 Full-Length 3-Hour NexusGate Mock Tests under real exam conditions.
  - Review mistake log and re-solve marked/bookmarked questions.`;
  }

  return `Nexus AI is ready to assist your GATE preparation! I can:
- Provide rigorous step-by-step derivations for any PYQ.
- Give subtle hints without revealing the full answer.
- Explain foundational engineering concepts.
- Generate similar practice questions tailored to your weak areas.
- Analyze your test attempts and recommend strategic focus areas.

What would you like to explore next?`;
}

// AI Chat Endpoint
app.post('/api/ai/chat', async (req: Request, res: Response) => {
  try {
    const { message, context } = req.body;

    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    if (ai) {
      try {
        const systemInstruction = `You are "Nexus AI", an elite GATE (Graduate Aptitude Test in Engineering) mentor and professor.
You possess deep expertise in Computer Science (CSE/IT), Electronics (ECE), Electrical (EE), Data Science & AI (DA), and Engineering Mathematics.
Your responses must be academically rigorous, clear, concise, and pedagogical.
Format mathematical expressions cleanly using LaTeX syntax ($...$ or $$...$$) or clean ASCII notation.
When discussing questions, highlight the core concept tested, common traps/mistakes that cost negative marks in GATE, and pro-shortcuts.
Context:
${context?.activeQuestion ? `Active Question ID: ${context.activeQuestion.id}
Subject: ${context.activeQuestion.subject}
Topic: ${context.activeQuestion.topic}
Question Text: ${context.activeQuestion.questionText}
Correct Answer: ${context.activeQuestion.correctAnswer}
Options: ${JSON.stringify(context.activeQuestion.options || [])}` : ''}
${context?.activeSubject ? `Active Subject: ${context.activeSubject}` : ''}
${context?.activeTopic ? `Active Topic: ${context.activeTopic}` : ''}
${context?.testResult ? `Recent Test Score: ${context.testResult.score}/${context.testResult.totalMarks}, Accuracy: ${context.testResult.accuracy}%` : ''}
`;

        const response = await ai.models.generateContent({
          model: 'gemini-3.8-flash',
          contents: message,
          config: {
            systemInstruction,
            temperature: 0.7,
          },
        });

        const reply = response.text || generateFallbackResponse(message, context);
        return res.json({ reply, model: 'gemini-3.8-flash' });
      } catch (geminiError: any) {
        console.warn('Gemini API call failed, using high-quality local knowledge fallback:', geminiError?.message);
        const fallback = generateFallbackResponse(message, context);
        return res.json({ reply: fallback, model: 'nexus-knowledge-engine' });
      }
    } else {
      const fallback = generateFallbackResponse(message, context);
      return res.json({ reply: fallback, model: 'nexus-knowledge-engine' });
    }
  } catch (error: any) {
    console.error('Server error in /api/ai/chat:', error);
    res.status(500).json({ error: 'Failed to process AI request' });
  }
});

// Vite middleware in dev or static files in production
async function startServer() {
  if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  } else {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  app.listen(port, () => {
    console.log(`NexusGate server running on http://localhost:${port}`);
  });
}

startServer();
